name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: release
      uses: actions/create-release@v1
      id: release_creation
      with:
        draft: false
        prerelease: false
        release_name: ${{GITHUB_RUN_NUMBER}}
        tag_name: ${{github.ref}}
    - name: upload windows artifact
        uses: actions/upload-artifact@v2.2.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/UniversalToolkit.windows-amd64.zip
          asset_name: UniversalToolkit.windows-amd64.zip
          asset_content_type: application/zip
      
